### ISSUE TITLE
Change ext yaml to yml

### ISSUE THREAD

**Issue by adisiji** [kigen/bitbucket-pipelines-android#1]
your file extension sholud be "yml" to be detected in Bitbucket

**Comment by kigen** [comment]
@adisiji 
Many thanks for the correction. 
Looking at my project scripts (pipelines activated projects) I am wondering why I named these ones with *.yaml   
🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️ 🤦‍♂️
